name: ci
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build Windows
        run: GOOS=windows GOARCH=386 go build -o driveignore.exe -v .

      - name: Build OSX
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'shilangyu/driveignore'
        continue-on-error: true
        run: GOOS=darwin GOARCH=amd64 go build -o driveignore.dmg -v .

      - name: Test
        run: go test ./...

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'shilangyu/driveignore'
        with:
          files: |
            driveignore.exe
            driveignore.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
